### ISSUE TITLE
How To Import into Jupyter Notebook

### ISSUE THREAD

**Issue by mmurray22** [kafonek/ipython_blocking#2]
Hello @kafonek ! Great work with this project-this is exactly what I'm looking for! However, I'm pretty new with using the online Jupyter Notebook interface, and I'm not sure what I'm missing but the ipython_blocking module is not being found. Here is the current cell I am running:

```
import os
import sys
from IPython.display import display
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import ipywidgets as widgets
import ipython_blocking 

```
However, I get an error saying:

`ImportError: No module named 'ipython_blocking'`

I can't seem to find an answer to this online-any suggestions? Thank you in advance!

**Comment by kafonek** [comment]
Thanks for the kind words @MMP3AC3.  `ipython_blocking` is on pypi so you should be able to `pip install ipython_blocking` in your Python environment, and then `import ipython_blocking` after that.  

If you did run `pip install ipython_blocking` but your Python instance can't import it, then I would guess that your default `pip` is using a different virtual environment than the Python instance you're trying to import into.  You'll have to explain a bit more about your set-up (running locally in Anaconda or Google Colab or Binder or somewhere else?). 

Thanks

**Comment by mmurray22** [comment]
Hello @kafonek,

I am currently running the program on a web-based Jupyter Notebook-can you still use pip install for that, or is there some other way to do it? I've tried looking it up, but searches seem to come up empty. Any ideas?

Thanks

**Comment by bryceschober** [comment]
@mmurray22 Did you try `%pip install ipython_blocking` in your notebook before the `import` statement?

**Comment by caggursoy** [comment]
Hi, sorry to resurrect the issue but I am having the same issue.

I am running a Jupyter-lab notebook with using Conda as the environment manager.
Surely, when I check the packages installed for the virtual-env I got the following result; which means that the package is installed.
`...`
`ipython                   8.14.0                   pypi_0    pypi`
`ipython-blocking          0.3.1                    pypi_0    pypi`
`ipython_genutils          0.2.0                      py_1    conda-forge`
`...`

Regardless, when I run the `import ipython-blocking` block it gives me the following error: `ModuleNotFoundError: No module named 'ipython_blocking'

Moreover I have tried your `%pip install ipython_blocking` approach but all I got is that all the dependencies are already installed and then the same error on the next `import ipython-blocking` line.

I would be glad if you can help me with that.
