### ISSUE TITLE
Support reading other properties than value?

### ISSUE THREAD

**Issue by bryceschober** [kafonek/ipython_blocking#6]
Now my problem is that I want to use it with `from ipyfilechooser import FileChooser`, which doesn't inherit from `ValueWidget` or have a `value` property or something:
```python
/opt/conda/lib/python3.7/site-packages/ipython_blocking/ipython_magic.py in block(self, line)
     57             func = lambda: obj._has_been_clicked
     58         else:
---> 59             raise Exception('The positional argument to %block should be a ValueWidget, Button, or a function/method')
     60         return self.capture(func, args.timeout)
     61 
```
If there were some way to point at a property: `%block myobject.property`, and somehow introspect that it was indeed a value or property to do change detection on, then it could be a good general-purpose solution. Also, `FileChooser` should probably actually inherit and provide a `value`, but that's another matter.

Yes, I know I can write a change-detecting function, as per the workaround in #5:
```python
# previous cell
config_selector = FileChooser(str(root_working_dir), use_dir_icons=True)
display(config_selector)

# next cell
ctx = ipython_blocking.CaptureExecution()
with ctx:
    init_val = config_selector.selected
    while True:
        if init_val != config_selector.selected:
            break
        ctx.step()
```

...but I was hoping for an easy-to-read magic one-liner.

**Comment by bryceschober** [comment]
Yes, I know I can write a change-detecting function, as per the workaround in #5, but I was hoping for an easy-to-read magic one-liner.

**Comment by bryceschober** [comment]
@kafonek After [I requested it](https://github.com/crahan/ipyfilechooser/issues/28), ipyfilechooser now inherits from `ValueWidget` and implements `get_interact_value()`, but that seems to not be enough for `ipython_blocking`...

**Comment by kafonek** [comment]
@bryceschober for any kind of situation where you're working with non-standard widgets or have some complex validation (like multiple widgets being filled out), the best thing to do with ipython_blocking is define a function to block on.  Basically at every step (`kernel.do_one_iteration()`) it will run your blocking function.  If the function returns True, it breaks out of the blocking context.  If not, it stays in the blocking context.

For `FileChooser`, try this out:

```
### cell 1
import ipyfilechooser
fc = ipyfilechooser.FileChooser()

def block_until_selected():
    return bool(fc.selected)

fc
```

```
### cell 2
import ipython_blocking

%block block_until_selected
```

```
### cell 3
### will not run until a file is selected in cell 1
fc.selected
```

**Comment by bryceschober** [comment]
Yep, that ended up being simpler, thanks.
